name: "Build Image and push"
on: 
  pull_request: 
    branches: ["main"]
    types: [closed]
    paths:
      - services/**

  push:
    branches:
      - main
      - testing1
    paths:
      - services/**
    tags:
      - "**@[0-9]*.[0-9]*.[0-9]*" # service/foo/bar@X.Y.Z

  workflow_dispatch:
    inputs:
      service:
        description: "Service to build"
        type: choice
        required: true
        options:
          - services/go/api-golang
          - services/node/api-node
          - services/other/api-golang-migrator
          - services/python/load-generator-python
          - services/react/client-react
      version:
        description: "Version/tag to use (optional; defaults generating with git describe)"
        required: false
        type: string

permissions:
  actions: write # used to trigger deploy workflow
  contents: read

jobs:
  filter:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    outputs:
      services: ${{ steps.set-output.outputs.services }}
      environment: ${{ steps.set-output.outputs.environment }}
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1

      - name: diff-check
        uses: dorny/paths-filter@v3
        id: filter
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          filters: .github/utils/file-filters.yaml
          base: main
      
      - name: set-output
        id: set-output
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "environment=development" >> "$GITHUB_OUTPUT"
            echo "services=[\"${{inputs.service}}\"]" >> "$GITHUB_OUTPUT"
          
          elif [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "environment=production" >> "$GITHUB_OUTPUT"
            tag="${GITHUB_REF_NAME}"
            svc="${tag%%@*}"
            echo "services=[\"${svc}\"]" >> "$GITHUB_OUTPUT"
          
          else
            echo "environment=staging" >> "$GITHUB_OUTPUT"
            json_services=$(echo '["services/python/load-generator-python"]' | jq -c '[.[] | tostring]')
            echo "services=$json_services" >> "$GITHUB_OUTPUT"
          fi
      - name: echo-outputs
        run: |
              echo Services="${{ steps.set-output.outputs.services }}"
              echo Environment="${{ steps.set-output.outputs.environment }}"
  
  build-container-image:
    runs-on: ubuntu-24.04
    if: ${{ needs.filter.outputs.services != '[]' && needs.filter.outputs.services != '' }}
    needs: ["filter"]
    strategy:
      fail-fast: false
      matrix:
        service: ${{ fromJson(needs.filter.outputs.services) }}
    environment: ${{ needs.filter.outputs.environment }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ matrix.service }}
    steps:
      - name: checkout
        uses: actions/checkout@v6.0.1
        with:
          fetch-depth: 0

      - name: set-up-task
        uses: ./.github/actions/setup-dependencies
        with:
          install-task: true

      - name: Login to Docker Hub
        if: ${{ !env.ACT }}
        uses: docker/login-action@v3
        with:
          username: ${{ vars.docker_username }}
          password: ${{ secrets.docker_access_token }} 
      
      - name: Set up QEMU
        if: ${{ !env.ACT }}
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        if: ${{ !env.ACT }}
        uses: docker/setup-buildx-action@v3

      - name: compute-image-tag
        id: compute-image-tag
        working-directory: ${{ matrix.service }}
        env:
          INPUT_VERSION: ${{ github.event_name == 'workflow_dispatch' && inputs.version || ''  }}
          ENVIRONMENT: ${{ needs.filter.outputs.environment }}
          SERVICE: ${{ matrix.service }}
        run: |
          if [[ -n "$INPUT_VERSION" ]]; then
            version="$INPUT_VERSION"
            image_tag=$(task utils:manual-version-tag VERSION="$INPUT_VERSION")
          
          elif [[ "$ENVIRONMENT" == "production" ]]; then
            echo "In elif"
            echo "Servicee=$SERVICE"
            version=$(task utils:generate-version -- "$SERVICE")
            echo "versionn=${version}"
            image_tag=$(task utils:generate-version-tag -- "$SERVICE") 

          else
            echo "In else"
            version=$(task utils:generate-extended-version -- "$SERVICE")
            image_tag=$(task utils:generate-extended-version-tag -- "$SERVICE")
          fi

          echo "image_tag=${image_tag}" >> "$GITHUB_OUTPUT"
          echo "version=${version}" >> "$GITHUB_OUTPUT"
          echo "image_taggg=${image_tag}"

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.service }}
          push: ${{ !env.ACT }} # Don't push images when running locally
          tags: ${{ steps.compute-image-tag.outputs.image_tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max


      - name: Install-gh-cli
        run: |
            (type -p wget >/dev/null || (sudo apt update && sudo apt install wget -y)) \
            && sudo mkdir -p -m 755 /etc/apt/keyrings \
            && out=$(mktemp) && wget -nv -O$out https://cli.github.com/packages/githubcli-archive-keyring.gpg \
            && cat $out | sudo tee /etc/apt/keyrings/githubcli-archive-keyring.gpg > /dev/null \
            && sudo chmod go+r /etc/apt/keyrings/githubcli-archive-keyring.gpg \
            && sudo mkdir -p -m 755 /etc/apt/sources.list.d \
            && echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main" | sudo tee /etc/apt/sources.list.d/github-cli.list > /dev/null \
            && sudo apt update \
            && sudo apt install gh -y

      - name: Trigger Deploy
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run update-gitops-manifests.yaml \
            -f service=${{ matrix.service }} \
            -f version=${{ steps.compute-image-tag.outputs.version }} \
            -f environment=${{ needs.filter.outputs.environment }}